/**
 * Extract structured content from legacy-pages/dashboard-templates/*.html
 * into a typed data file data/dashboard-templates.ts
 *
 * Usage: npx tsx scripts/extract-dashboard-templates.ts
 */

import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import * as cheerio from "cheerio";

const LEGACY_DIR = join(process.cwd(), "legacy-pages/dashboard-templates");
const OUTPUT_FILE = join(process.cwd(), "data/dashboard-templates.ts");

type FaqItem = { question: string; answerHtml: string };

type DashboardFeatureBlock = {
  heading: string;
  bodyHtml: string;
  image: string;
  imageSrcSet?: string;
  imageAlt: string;
  reverse: boolean;
};

type DashboardTemplatePageData = {
  slug: string;
  metaTitle: string;
  metaDescription: string;
  canonical: string;
  heroTitle: string;
  heroSubtitleHtml: string;
  featureBlocks: DashboardFeatureBlock[];
  ctaTitleHtml: string;
  ctaBodyHtml: string;
  faq: FaqItem[];
};

function rewriteImagePath(p: string): string {
  // Legacy paths are "../images/foo.webp" -> "/images/foo.webp"
  // Also rewrite srcset entries
  return p.replace(/\.\.\/images\//g, "/images/");
}

function getInnerHtml($: cheerio.CheerioAPI, sel: cheerio.Cheerio<any>): string {
  return (sel.html() ?? "").trim();
}

function extractOne(slug: string, file: string): DashboardTemplatePageData {
  const html = readFileSync(file, "utf8");
  const $ = cheerio.load(html);

  const metaTitle = $("title").first().text().trim();
  const metaDescription = ($('meta[name="description"]').attr("content") ?? "").trim();
  const canonical = ($('link[rel="canonical"]').attr("href") ?? "").trim();

  // HERO: .blog_hero-section > .heading-left-text-wr > h1 + .heading-style-h6
  const hero = $(".blog_hero-section").first();
  const heroTitle = hero.find("h1.heading-style-h1").first().text().trim();
  const heroSubtitleEl = hero.find(".heading-style-h6").first();
  const heroSubtitleHtml = rewriteImagePath(getInnerHtml($, heroSubtitleEl));

  // FEATURE BLOCKS: every .template_2col-cards
  const featureBlocks: DashboardFeatureBlock[] = [];
  $(".template_2col-cards").each((_, el) => {
    const $block = $(el);
    const reverse = $block.hasClass("is-reverse");

    // Find the text side: .template-list-text-wr.is-only-text-item
    const textWrap = $block.find(".template-list-text-wr.is-only-text-item").first();
    const heading = textWrap.find("h2").first().text().trim();
    const richText = textWrap.find(".w-richtext").first();
    const bodyHtml = rewriteImagePath(getInnerHtml($, richText));

    // Find the image: img inside .template-list-item-is-only-img
    const img = $block.find(".template-list-item-is-only-img img").first();
    const imageRaw = img.attr("src") ?? "";
    const srcsetRaw = img.attr("srcset") ?? "";
    const imageAlt = img.attr("alt") ?? "";

    const image = rewriteImagePath(imageRaw);
    const imageSrcSet = srcsetRaw ? rewriteImagePath(srcsetRaw) : undefined;

    featureBlocks.push({
      heading,
      bodyHtml,
      image,
      imageSrcSet,
      imageAlt,
      reverse,
    });
  });

  // CTA: .main_cta-section h2 + .heading-style-h5
  const cta = $(".main_cta-section").first();
  const ctaTitleHtml = rewriteImagePath(getInnerHtml($, cta.find("h2.heading-style-h2").first()));
  const ctaBodyHtml = rewriteImagePath(getInnerHtml($, cta.find(".heading-style-h5").first()));

  // FAQ: every .faq_item-wrapper
  const faq: FaqItem[] = [];
  $(".faq_item-wrapper").each((_, el) => {
    const $item = $(el);
    const question = $item.find(".faq_question > p").first().text().trim();
    const answerEl = $item.find(".faq_answer .w-richtext").first();
    const answerHtml = rewriteImagePath(getInnerHtml($, answerEl));
    faq.push({ question, answerHtml });
  });

  return {
    slug,
    metaTitle,
    metaDescription,
    canonical,
    heroTitle,
    heroSubtitleHtml,
    featureBlocks,
    ctaTitleHtml,
    ctaBodyHtml,
    faq,
  };
}

function main() {
  const files = readdirSync(LEGACY_DIR).filter((f) => f.endsWith(".html")).sort();
  const all: DashboardTemplatePageData[] = [];
  for (const f of files) {
    const slug = f.replace(/\.html$/, "");
    const full = join(LEGACY_DIR, f);
    const data = extractOne(slug, full);
    all.push(data);
    console.error(
      `✓ ${slug}: title="${data.metaTitle.slice(0, 40)}..." features=${data.featureBlocks.length} faq=${data.faq.length}`,
    );
  }

  // Serialize — write as TS source with a stable ordering
  const lines: string[] = [];
  lines.push("// AUTO-GENERATED by scripts/extract-dashboard-templates.ts");
  lines.push('// Source: legacy-pages/dashboard-templates/*.html');
  lines.push("// Do not edit by hand — re-run the script to regenerate.");
  lines.push("");
  lines.push('import type { FaqItem, BreadcrumbItem } from "../types/data";');
  lines.push("");
  lines.push("export type DashboardFeatureBlock = {");
  lines.push("  heading: string;");
  lines.push("  bodyHtml: string;");
  lines.push("  image: string;");
  lines.push("  imageSrcSet?: string;");
  lines.push("  imageAlt: string;");
  lines.push("  reverse: boolean;");
  lines.push("};");
  lines.push("");
  lines.push("export type DashboardTemplatePageData = {");
  lines.push("  slug: string;");
  lines.push("  metaTitle: string;");
  lines.push("  metaDescription: string;");
  lines.push("  canonical: string;");
  lines.push("  ogImage: string;");
  lines.push("  breadcrumbs: BreadcrumbItem[];");
  lines.push("  heroTitle: string;");
  lines.push("  heroSubtitleHtml: string;");
  lines.push("  featureBlocks: DashboardFeatureBlock[];");
  lines.push("  ctaTitleHtml: string;");
  lines.push("  ctaBodyHtml: string;");
  lines.push("  faq: FaqItem[];");
  lines.push("};");
  lines.push("");
  lines.push(
    'const OG_IMAGE = "https://cdn.prod.website-files.com/64cc98fb252732dec5bda7e9/65a66f06e0e919d7d7e3e8d5_setproduct2.jpg";',
  );
  lines.push("");
  lines.push("const BREADCRUMBS: BreadcrumbItem[] = [");
  lines.push('  { label: "Home", href: "/" },');
  lines.push('  { label: "Templates", href: "/all" },');
  lines.push('  { label: "Dashboards" },');
  lines.push("];");
  lines.push("");
  lines.push("export const DASHBOARD_TEMPLATES: DashboardTemplatePageData[] = [");
  for (const d of all) {
    lines.push("  {");
    lines.push(`    slug: ${JSON.stringify(d.slug)},`);
    lines.push(`    metaTitle: ${JSON.stringify(d.metaTitle)},`);
    lines.push(`    metaDescription: ${JSON.stringify(d.metaDescription)},`);
    lines.push(`    canonical: ${JSON.stringify(d.canonical)},`);
    lines.push("    ogImage: OG_IMAGE,");
    lines.push("    breadcrumbs: BREADCRUMBS,");
    lines.push(`    heroTitle: ${JSON.stringify(d.heroTitle)},`);
    lines.push(`    heroSubtitleHtml: ${JSON.stringify(d.heroSubtitleHtml)},`);
    lines.push("    featureBlocks: [");
    for (const b of d.featureBlocks) {
      lines.push("      {");
      lines.push(`        heading: ${JSON.stringify(b.heading)},`);
      lines.push(`        bodyHtml: ${JSON.stringify(b.bodyHtml)},`);
      lines.push(`        image: ${JSON.stringify(b.image)},`);
      if (b.imageSrcSet) {
        lines.push(`        imageSrcSet: ${JSON.stringify(b.imageSrcSet)},`);
      }
      lines.push(`        imageAlt: ${JSON.stringify(b.imageAlt)},`);
      lines.push(`        reverse: ${b.reverse ? "true" : "false"},`);
      lines.push("      },");
    }
    lines.push("    ],");
    lines.push(`    ctaTitleHtml: ${JSON.stringify(d.ctaTitleHtml)},`);
    lines.push(`    ctaBodyHtml: ${JSON.stringify(d.ctaBodyHtml)},`);
    lines.push("    faq: [");
    for (const q of d.faq) {
      lines.push("      {");
      lines.push(`        question: ${JSON.stringify(q.question)},`);
      lines.push(`        answerHtml: ${JSON.stringify(q.answerHtml)},`);
      lines.push("      },");
    }
    lines.push("    ],");
    lines.push("  },");
  }
  lines.push("];");
  lines.push("");
  lines.push(
    "export function getDashboardTemplateBySlug(slug: string): DashboardTemplatePageData | undefined {",
  );
  lines.push("  return DASHBOARD_TEMPLATES.find((d) => d.slug === slug);");
  lines.push("}");
  lines.push("");

  writeFileSync(OUTPUT_FILE, lines.join("\n"), "utf8");
  console.error(`\n✓ Wrote ${OUTPUT_FILE} (${all.length} entries)`);
}

main();
